### ISSUE TITLE
TFTP timeout loading initrd on PXE boot

### ISSUE THREAD

**Issue by labbyjoel** [brainupdaters/drlm#135] opened 2020-02-19 11:05 UTC
Hello ! 

I'm reffering to issue #92 

i've got exactly the same issue, but I cannot understand the response given 

_"this issue is because of the driver VMXNET3, try to create a new network interface with E1000 , it should work."_

this response seems to resolve te user problem as he said 

_"Thank you, that did the trick."_

Could you explain me what you want to tell him ? And where can I try to search resolving this issue  ? 
thanks ! 

Joël

**Comment by didacog** [comment] 2020-02-25 07:39
Hello @labbyjoel,

If you are using VMWare, the solution is related to the network driver used. VMWare vmxnetX drivers do not support PXE boot, so to be able to do netboot, must be changed to e1000 driver in VM settings.

Sorry for the late response, we've been busy last days...

Regards,
Didac

**Comment by didacog** [comment] 2020-03-02 12:41
@labbyjoel, any update on this? 

if not we'll close this issue. You'll be able to reopen it if needed.

Regards,
Didac

**Comment by labbyjoel** [comment] 2020-03-02 13:01
Hello Didac ! 
Sorry for the late response... I was sick last week... 
I don't use vmware. All the computers used for this test are 'real' one. 
The computer on witch I 've got the problem is a dell poweredge 1950.

**Comment by didacog** [comment] 2020-03-02 13:55
Hello, 
Ok, then can you configure tftp service with -vvv and attach the output of /var/log/messages lines?

also attach the tftp service config please.

Regards,
Didac

**Comment by labbyjoel** [comment] 2020-03-02 13:57
I will do that asap !

**Comment by labbyjoel** [comment] 2020-03-02 14:08
here is the tftp config : 

```
service tftp
{
        socket_type             = dgram
        protocol                = udp
        wait                    = yes
        user                    = root
        server                  = /usr/sbin/in.tftpd
        server_args             = -s /home/drlm/store -vvv
        disable                 = no
        per_source              = 11
        cps                     = 100 2
        flags                   = IPv4
        log_type                = FILE /var/log/tftp.log
}
```


the content of /var/log/messages

```
Mar  2 15:58:01 testdrlm dhcpd: DHCPDISCOVER from 00:1e:c9:b0:e5:9c via eno1
Mar  2 15:58:01 testdrlm dhcpd: DHCPOFFER on 192.9.200.10 to 00:1e:c9:b0:e5:9c via eno1
Mar  2 15:58:01 testdrlm systemd: Started Session 21636 of user root.
Mar  2 15:58:01 testdrlm systemd: Starting Session 21636 of user root.
Mar  2 15:58:05 testdrlm dhcpd: DHCPREQUEST for 192.9.200.10 (192.9.200.148) from 00:1e:c9:b0:e5:9c via eno1
Mar  2 15:58:05 testdrlm dhcpd: DHCPACK on 192.9.200.10 to 00:1e:c9:b0:e5:9c via eno1
Mar  2 15:58:05 testdrlm in.tftpd[2296]: RRQ from 192.9.200.10 filename boot/grub/i386-pc/core.0
Mar  2 15:58:05 testdrlm in.tftpd[2296]: Error code 0: TFTP Aborted
Mar  2 15:58:05 testdrlm in.tftpd[2297]: RRQ from 192.9.200.10 filename boot/grub/i386-pc/core.0
Mar  2 15:58:05 testdrlm in.tftpd[2297]: Client 192.9.200.10 finished boot/grub/i386-pc/core.0

```
and the content of var/log/tftpd.log

`20/3/2@15:58:05: START: tftp pid=2295 from=192.9.200.10`

**Comment by didacog** [comment] 2020-03-02 14:34
can you do ls -lR of /home/drlm?

As you use different ARCHDIR/STORDIR locations may be a permissions problem.

Also, please post the output of:

drlm listclient -A
drlm listnetwork -A 

Thanks!
didac

**Comment by labbyjoel** [comment] 2020-03-02 14:48
This server is not the same than the one you already debug . 

In the process of my tests, I did this test : 

1° archiving a computer on the first serveur
2° exporting the archive
3° creating a fresh new networks with just one drlm server / one switch / one computer on which I want to restore the archive 
4° Creating a new client on the server
5° importing the archive for this client
6 trying to noot this client. 

Result of drlm listclient -A

```
Id     Name            MacAddres       Ip               Client OS        ReaR Version     Network         Scheduled
101    scripts4        001ec9b0e59c    192.9.200.10                                       nWave2          False  
```

Result of drlm listnetwork -A

```
Id     Ip              Mask            Gw              Broadcast       Server Ip       Name                                     
1      192.9.200.0     255.255.252.0   192.9.200.150   192.9.203.255   192.9.200.148   nWave2  
```

and the ls result 

[ls.txt](https://github.com/brainupdaters/drlm/files/4275975/ls.txt)

**Comment by didacog** [comment] 2020-03-03 07:44
Hello,
The process is perfect for testing ;)

the problem with PXE could be different things... :_(

The orig client and the dest client are the same platform (BIOS - BIOS)?
The server has the firewall/selinux disabled or properly configured to allow correct comms?
The dest server NIC firmware is OK?
The switch/cable are OK?

The permissions seem correct, ...

Can you test booting the same image in a VM in the same Network, from your laptop with bridged network, for example? just to compare results and see if we can discard possibilities.

Regards,
Didac

**Comment by labbyjoel** [comment] 2020-03-03 09:44
Here are the answers : 

The orig and dest clients are not the same plarforms. ( I've test the new platform with another PXE server ( the one used to deploy our OS - It works well. 

firewall and selinux are disabled on the serveur.

I've tested with another dest client computer ( a laptop ) and this worked. 

It will be interresting to have a log from the client side.. but I don't know how to get it...

**Comment by didacog** [comment] 2020-03-03 10:54
The problem is that the client side is the NIC firmware of your DELL Poweredge 1950. 
Did you check if Firmware is up to date?

**Comment by labbyjoel** [comment] 2020-03-03 13:35
I've just upgraded the firmware on this client. But the result is unfortunately the same... 

I cannot understand why it works with ou internal pxe server and not with the drlm one...

**Comment by didacog** [comment] 2020-03-04 10:44
Hello @labbyjoel,
What your internal PXE server is? maybe we can figure it out what is happening...

I've found some posts/maillists about problems PXE booting some Dell PE on Linux. 
Does this server have 2 NICs? can you test disabling PXE on the one not used for DRLM?

Regards,
Didac

**Comment by labbyjoel** [comment] 2020-03-04 10:49
This computer is a bit old... I've tried with another one ( poweredge R410 ) and it's working like a charm... 

I don't think we need to spend more time on this computer unless you really want to find the problem...

**Comment by didacog** [comment] 2020-03-04 11:08
Well ... is up to you... we do not have the HW to test it, so if you can test it and want to try to solve the issue we can try to help as much as we can, but if not, we can close the issue and anybody can reopen it if needed in the future.

Your choice.. ;)

Kind regards,
Didac

**Comment by labbyjoel** [comment] 2020-03-04 11:31
I've just ended the recover on the R410 without any problems. 

This old material is just used for testing purpose and I don't plan to put it on production anymore.. 

I think you can close this issue...  And keeping in mind this problem with PE1950 :-) 

Thanks a lot and sorry for the time...

**Comment by didacog** [comment] 2020-03-04 11:41
Ok, thanks to you for the testing!

The issue will be here forever, and can be reopened by anyone if needed. So is as far as searching for it and reopening :-P

Please let us know if you end implementing DRLM in production and if is not asking a lot, if we can inform that your company is using DRLM in the drlm.org website. ;)

So... closing the issue.

Kind regards,
Didac

**Closed by didacog** 2020-03-04 11:41 UTC
Labels: question
