### ISSUE TITLE
service not working on systemd

### ISSUE THREAD

**Issue by aolle** [brainupdaters/drlm#14] opened 2015-12-09 19:39 UTC
Hi,

I've had problems starting drlm-stord service. I think so it's a systemd compatibility problem.

root@minidebian:/tmp# service drlm-stord start
root@minidebian:/tmp# service drlm-stord status
● drlm-stord.service - LSB: DRLM Store Service
   Loaded: loaded (/etc/init.d/drlm-stord)
   Active: active (exited) since mar 2015-12-08 23:22:50 CET; 4min 14s ago
  Process: 22466 ExecStart=/etc/init.d/drlm-stord start (code=exited, status=0/SUCCESS)

dic 08 23:22:50 minidebian drlm-stord[22466]: [....] Starting DRLM Store Service:.
dic 08 23:22:50 minidebian drlm-stord[22466]: Starting DRLM Store Service:.
dic 08 23:22:50 minidebian systemd[1]: Started LSB: DRLM Store Service.
dic 08 23:23:07 minidebian systemd[1]: Started LSB: DRLM Store Service.
dic 08 23:27:02 minidebian systemd[1]: Started LSB: DRLM Store Service.

Nothing echoes and the service won't start properly.

thanks.

**Comment by Flukas88** [comment] 2016-02-05 09:40
I think what is missing is a systemd unit.

**Comment by didacog** [comment] 2016-02-05 09:58
Hi,

Yes, a systemd unit is missing because DRLM is not well tested yet on systemd. At this time is well tested with Debian 6/7 and  CentOS-RHEL 5/6. 
Is planned in roadmap. 
I guess with a simple systemd unit should work without problems.

thx!

**Comment by proura** [comment] 2016-07-08 18:35
Now DRLM supports systemd init system. The service is automatically installed as well as for systemd as init.

**Comment by didacog** [comment] 2016-07-27 12:49
I've tested with centos7 and is working well. 

IMHO this issue is solved.

**Comment by didacog** [comment] 2016-07-31 19:12
Tested also with debian 8 and no regression on previous versions. Closing.

**Closed by didacog** 2016-07-31 19:12 UTC
Labels: enhancement
